package com.damon43.polyjoy.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.damon43.polyjoy.bean.RecordableBean;

import com.damon43.polyjoy.db.RecordableBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordableBeanDaoConfig;

    private final RecordableBeanDao recordableBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordableBeanDaoConfig = daoConfigMap.get(RecordableBeanDao.class).clone();
        recordableBeanDaoConfig.initIdentityScope(type);

        recordableBeanDao = new RecordableBeanDao(recordableBeanDaoConfig, this);

        registerDao(RecordableBean.class, recordableBeanDao);
    }
    
    public void clear() {
        recordableBeanDaoConfig.clearIdentityScope();
    }

    public RecordableBeanDao getRecordableBeanDao() {
        return recordableBeanDao;
    }

}
